{% set version = "1.3.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mets/mets_{{ version }}.tar.gz
  sha256: 733ce39743148082b0fe7aa7158d213c3bea2689a8d0eb452bb409dc39cb3591

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-lava >=1.6.6
    - r-mvtnorm
    - r-numderiv
    - r-survival >=2.43_1
    - r-timereg >=1.9.4
    - libblas
    - liblapack
  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-lava >=1.6.6
    - r-mvtnorm
    - r-numderiv
    - r-survival >=2.43_1
    - r-timereg >=1.9.4

test:
  commands:
    - $R -e "library('mets')"           # [not win]
    - "\"%R%\" -e \"library('mets')\""  # [win]

about:
  home: https://kkholst.github.io/mets/
  license: GPL-2.0-or-later
  summary: Implementation of various statistical models for multivariate event history data <doi:10.1007/s10985-013-9244-x>. Including multivariate cumulative incidence models <doi:10.1002/sim.6016>, and  bivariate random effects probit models (Liability models) <doi:10.1016/j.csda.2015.01.014>. Also contains two-stage binomial
    modelling that can do pairwise odds-ratio dependence modelling based marginal logistic regression models. This is an alternative to the alternating logistic regression approach (ALR).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
